version: '3.9'
services:
  spark:
    image: 'docker.io/bitnami/spark:3.1.2'
    volumes:
      - type: bind
        source: ./data
        target: /opt/data
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '7077:7077'
      - '18080:8080'
  spark-worker-1:
    image: docker.io/bitnami/spark:3.1.2
    volumes:
      - type: bind
        source: ./data
        target: /opt/data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  postgres:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    image: testcomplete:1.0.0
    volumes:
      - type: bind
        source: ./data
        target: /opt/data
    depends_on:
      - spark
      - spark-worker-1